[package]
name = "chess_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
chess_core = { path = "../chess_core" }
chess_engine = { path = "../chess_engine" }
futures-lite = "1.13.0"
rayon = "1.8.0" 