[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chess_core = { path = "../chess_core" }
thiserror = { workspace = true }
log = { workspace = true }
rayon = "1.8.0"
rand = "0.8.5"
once_cell = "1.18.0" 